from __future__ import annotations


HYDRA_BOSS_MODULE = {
    "boss_key": "hydra",
    "label": "Hydra",
    "category": "Clan Boss",
    "optimizer_status": "active",
    "implemented_in_optimizer": True,
    "team_size": 6,
    "default_level": "normal",
    "default_affinity": "rotation_1",
    "overview": "Boss a sei teste con meccaniche rotanti. Qui non basta la stat line: servono risposte giuste ai singoli head e un team con utility distribuita.",
    "levels": [
        {
            "key": "normal",
            "label": "Normal",
            "stat_targets": [
                {"label": "Speed floor", "value": "190 SPD", "confidence": "medium", "note": "Baseline euristica del motore per tenere il giro Hydra pulito."},
                {"label": "Accuracy floor", "value": "220 ACC", "confidence": "medium", "note": "Per Block Buffs, Provoke e Hex in progression normale."},
                {"label": "Resistance lane", "value": "250 RES", "confidence": "low", "note": "Utile sui support piu esposti e come base iniziale per Mischief tank."},
            ],
            "notes": ["La priorita vera e coprire le teste giuste, non inseguire un singolo numero magico."],
        },
        {
            "key": "hard",
            "label": "Hard",
            "stat_targets": [
                {"label": "Speed floor", "value": "215 SPD", "confidence": "medium", "note": "Baseline euristica usata dall'optimizer su Hydra Hard."},
                {"label": "Accuracy floor", "value": "270 ACC", "confidence": "medium", "note": "Serve far passare Block Buffs, Provoke e Hex con piu continuita."},
                {"label": "Resistance lane", "value": "320 RES", "confidence": "medium", "note": "Specialmente sul Mischief tank; Perfect Veil aiuta ma non sostituisce tutta la RES."},
            ],
            "notes": ["Hard inizia a punire team che non hanno copertura vera su Block Buffs e Provoke."],
        },
        {
            "key": "brutal",
            "label": "Brutal",
            "stat_targets": [
                {"label": "Speed floor", "value": "230 SPD", "confidence": "medium", "note": "La rotazione delle teste punisce buchi nei cooldown."},
                {"label": "Accuracy floor", "value": "330 ACC", "confidence": "medium", "note": "Per utility chiave in brutal senza troppe cadute di consistenza."},
                {"label": "Resistance lane", "value": "390 RES", "confidence": "medium", "note": "Specialmente support e Mischief tank."},
            ],
            "notes": ["A questo livello servono comp con utility sovrapposte e ruoli molto chiari."],
        },
        {
            "key": "nightmare",
            "label": "Nightmare",
            "stat_targets": [
                {"label": "Speed floor", "value": "245 SPD", "confidence": "medium", "note": "Nightmare Hydra richiede turn cycle molto pulito."},
                {"label": "Accuracy floor", "value": "380 ACC", "confidence": "medium", "note": "Le utility chiave devono restare consistenti anche nelle rotazioni peggiori."},
                {"label": "Resistance lane", "value": "470 RES", "confidence": "medium", "note": "Mischief tank dedicato e support critici devono stare su una lane alta."},
            ],
            "notes": ["Nightmare Hydra e piu un problema di architettura team che di singolo build score."],
        },
    ],
    "affinities": [
        {"key": "rotation_1", "label": "Rotazione 1"},
        {"key": "rotation_2", "label": "Rotazione 2"},
        {"key": "rotation_3", "label": "Rotazione 3"},
        {"key": "rotation_4", "label": "Rotazione 4"},
        {"key": "rotation_5", "label": "Rotazione 5"},
    ],
    "rotations": {
        "rotation_1": {
            "label": "Rotazione 1",
            "starter_heads": ["Decay", "Torment", "Suffering", "Mischief"],
            "substitute_heads": ["Blight", "Wrath"],
            "head_affinities": {
                "Decay": "Force",
                "Torment": "Magic",
                "Suffering": "Spirit",
                "Mischief": "Spirit",
                "Blight": "Magic",
                "Wrath": "Force",
            },
            "optimizer_focus": [
                "Provoke forte per Decay",
                "Perfect Veil o Shamael per Torment",
                "Mischief tank o Block Buffs molto stabile",
            ],
        },
        "rotation_2": {
            "label": "Rotazione 2",
            "starter_heads": ["Blight", "Torment", "Mischief", "Wrath"],
            "substitute_heads": ["Decay", "Suffering"],
            "head_affinities": {
                "Blight": "Force",
                "Torment": "Spirit",
                "Mischief": "Force",
                "Wrath": "Magic",
                "Decay": "Magic",
                "Suffering": "Force",
            },
            "optimizer_focus": [
                "Perfect Veil o Shamael per Torment",
                "Block Buffs per Blight e Mischief",
                "Mitigazione danni e Decrease ATK per Wrath",
            ],
        },
        "rotation_3": {
            "label": "Rotazione 3",
            "starter_heads": ["Decay", "Blight", "Suffering", "Wrath"],
            "substitute_heads": ["Torment", "Mischief"],
            "head_affinities": {
                "Decay": "Spirit",
                "Blight": "Spirit",
                "Suffering": "Magic",
                "Wrath": "Spirit",
                "Torment": "Force",
                "Mischief": "Magic",
            },
            "optimizer_focus": [
                "Provoke per Decay",
                "Block Buffs per Blight",
                "Mitigazione danni forte per Wrath",
            ],
        },
        "rotation_4": {
            "label": "Rotazione 4",
            "starter_heads": ["Decay", "Blight", "Mischief", "Wrath"],
            "substitute_heads": ["Torment", "Suffering"],
            "head_affinities": {
                "Decay": "Force",
                "Blight": "Magic",
                "Mischief": "Spirit",
                "Wrath": "Magic",
                "Torment": "Force",
                "Suffering": "Magic",
            },
            "optimizer_focus": [
                "Provoke per Decay",
                "Block Buffs per Blight e Mischief",
                "Mischief tank e mitigazione per Wrath",
            ],
        },
        "rotation_5": {
            "label": "Rotazione 5",
            "starter_heads": ["Decay", "Blight", "Suffering", "Mischief"],
            "substitute_heads": ["Torment", "Wrath"],
            "head_affinities": {
                "Decay": "Magic",
                "Blight": "Force",
                "Suffering": "Force",
                "Mischief": "Spirit",
                "Torment": "Magic",
                "Wrath": "Spirit",
            },
            "optimizer_focus": [
                "Provoke per Decay",
                "Block Buffs per Blight e Suffering",
                "Mischief tank o Block Buffs molto stabile",
            ],
        },
    },
    "mechanics": [
        {"label": "Rotating heads", "summary": "Le teste cambiano e obbligano la comp a coprire utility diverse nello stesso fight."},
        {"label": "Poison Cloud e buff pressure", "summary": "Block Buffs e la rimozione dei buff avversari tengono sotto controllo le teste piu fastidiose."},
        {"label": "Devour e Life Barrier", "summary": "Serve burst mirato e controllo della finestra in cui liberare il campione divorato."},
        {"label": "Mischief targeting", "summary": "Perfect Veil, buff management e un tank coerente valgono tantissimo."},
    ],
    "key_roles": [
        {"label": "Block Buffs", "reason": "E una delle utility piu centrali per tenere Hydra ordinata."},
        {"label": "Provoke", "reason": "Serve per fermare teste che altrimenti sballano il fight."},
        {"label": "Hex", "reason": "Aiuta sia danno sia liberazione del target divorato."},
        {"label": "Cleanse / Heal / Revive", "reason": "Hydra punisce le comp troppo lineari o senza recovery."},
        {"label": "Mischief tank", "reason": "Una lane dedicata semplifica tantissimo il fight."},
    ],
    "watchouts": [
        "Un team con solo danno e senza Block Buffs o Provoke di solito implode presto.",
        "Hydra va ottimizzata per head mechanics e rotazione, non solo per il boss selezionato in astratto.",
        "Molte soglie esatte ACC / RES dipendono da difficulty e rotazione: per ora le teniamo come target qualitativi, non hardcoded.",
    ],
    "timing_notes": [
        "La finestra devour e la gestione di Poison Cloud meritano un modulo dedicato piu avanti.",
        "Perfect Veil, buff count e targeting Mischief vanno trattati come logica separata nello scoring futuro.",
    ],
    "optimizer_gaps": [
        "Lo scoring Hydra e gia attivo, ma non modella ancora head rotation reale e devour timing in modo simulato.",
        "Mischief tank e Perfect Veil sono valutati come segnali forti, ma non esiste ancora una simulazione completa del targeting.",
        "Per la Rotazione 4 l'affinita di Suffering e trattata come inferenza community: la pagina HellHades ha un typo evidente sul quinto/sesto head.",
    ],
    "sources": [
        {
            "label": "Plarium - Guide: The Hydra",
            "url": "https://raid-support.plarium.com/hc/en-us/articles/4411876951442-Guide-The-Hydra",
            "kind": "official",
            "confidence": "high",
            "checked_at": "2026-04-04",
            "note": "Meccaniche base delle teste e struttura del contenuto.",
        },
        {
            "label": "HellHades - Getting Started With Hydra Clan Boss",
            "url": "https://hellhades.com/getting-started-with-hydra-clan-boss-in-raid-shadow-legends/",
            "kind": "community",
            "confidence": "medium",
            "checked_at": "2026-04-04",
            "note": "Ruoli chiave, utility consigliate e approccio progression.",
        },
        {
            "label": "HellHades - Hydra Clan Boss Seasons",
            "url": "https://hellhades.com/hydra-clan-boss-seasons/",
            "kind": "community",
            "confidence": "medium",
            "checked_at": "2026-04-04",
            "note": "Sequenza delle rotazioni/stagioni Hydra.",
        },
        {
            "label": "HellHades - Rotation 1 Breakdown",
            "url": "https://hellhades.com/rotation-1-breakdown-hydra-clan-boss-guide/",
            "kind": "community",
            "confidence": "medium",
            "checked_at": "2026-04-04",
            "note": "Starter heads e affinita per Rotazione 1.",
        },
        {
            "label": "HellHades - Rotation 2 Breakdown",
            "url": "https://hellhades.com/rotation-2-breakdown-hydra-clan-boss-guide/",
            "kind": "community",
            "confidence": "medium",
            "checked_at": "2026-04-04",
            "note": "Starter heads e affinita per Rotazione 2.",
        },
        {
            "label": "HellHades - Rotation 3 Breakdown",
            "url": "https://hellhades.com/rotation-3-breakdown-hydra-clan-boss-guide/",
            "kind": "community",
            "confidence": "medium",
            "checked_at": "2026-04-04",
            "note": "Starter heads e affinita per Rotazione 3.",
        },
        {
            "label": "HellHades - Rotation 4 Breakdown",
            "url": "https://hellhades.com/rotation-4-breakdown-hydra-clan-boss-guide/",
            "kind": "community",
            "confidence": "low",
            "checked_at": "2026-04-04",
            "note": "Starter heads confermati; l'affinita di Suffering e ricostruita da un typo evidente nella sezione affinity del breakdown.",
        },
        {
            "label": "HellHades - Rotation 5 Breakdown",
            "url": "https://hellhades.com/rotation-5-breakdown-hydra-clan-boss-guide/",
            "kind": "community",
            "confidence": "medium",
            "checked_at": "2026-04-04",
            "note": "Starter heads e affinita per Rotazione 5.",
        },
    ],
}
